back_administration:
    resource: "@BackAdministrationBundle/Resources/config/routing/administration.yml"
    prefix:   /administration

back_booking:
    resource: "@BackAdministrationBundle/Resources/config/routing/booking.yml"
    prefix:   /booking

back_administration_homepage:
    path:     /
    defaults: { _controller: BackAdministrationBundle:Default:index }
