services:
    mailerService:
        class: Back\AdministrationBundle\Services\MailerService
        arguments:
            - @doctrine.orm.entity_manager
            - @session
            - @service_container
            - @mailer
            - @templating