back_user:
    resource: "@BackUserBundle/Resources/config/routing.yml"
    prefix:   /

front_general:
    resource: "@FrontGeneralBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"