back_homepage:
    resource: "@BackAdministrationBundle/Resources/config/routing.yml"
    prefix:   /admin

back_user:
    resource: "@BackUserBundle/Resources/config/routing.yml"
    prefix:   /admin

front_general:
    resource: "@FrontGeneralBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"