Front_BabySitter_Profile_myprofile:
    path:     /MyProfile
    defaults: { _controller: FrontGeneralBundle:ProfileBabySitter:profile }

Front_BabySitter_Profile_ajax_to_address:
    path:     /ajax_to_address
    defaults: { _controller: FrontGeneralBundle:ProfileBabySitter:ajaxToAddress }

Front_BabySitter_Profile_mycalendar:
    path:     /MyCalendar/{id}
    defaults: { _controller: FrontGeneralBundle:ProfileBabySitter:calendar,id:null }

Front_BabySitter_Profile_listBooking:
    path:     /listBooking/{page}
    defaults: { _controller: FrontGeneralBundle:ProfileBabySitter:listBooking,page:1 }

Front_BabySitter_Profile_validate:
    path:     /listBooking_validate/{id}
    defaults: { _controller: FrontGeneralBundle:ProfileBabySitter:validate}