back_user_babysiter_listes:
    path:     /liste/{page}/{validated}
    defaults: { _controller: BackUserBundle:BabySitter:liste,page:1,validated:all }

back_user_babysiter_details:
    path:     /details/{id}
    defaults: { _controller: BackUserBundle:BabySitter:details }

back_user_babysiter_enable:
    path:     /enable/{id}
    defaults: { _controller: BackUserBundle:BabySitter:enable }

back_user_babysiter_validated:
    path:     /validated/{id}
    defaults: { _controller: BackUserBundle:BabySitter:validated }

back_user_babysiter_edit:
    path:     /edit/{id}
    defaults: { _controller: BackUserBundle:BabySitter:edit }