front_homepage:
    path:     /
    defaults: { _controller: FrontGeneralBundle:Default:homePage }

Front_BabySitter_Profile:
    resource: "@FrontGeneralBundle/Resources/config/routing/BabySitter.yml"
    prefix:   /baby_sitter_space

front_babysitter_liste:
    path:     /liste/{page}
    defaults: { _controller: FrontGeneralBundle:BabySitter:liste,page:1 }

front_babysitter_profile:
    path:     /babysitter/{slug}
    defaults: { _controller: FrontGeneralBundle:BabySitter:babysiter,page:1 }
