front_homepage:
    path:     /
    defaults: { _controller: FrontGeneralBundle:Default:homePage }

Front_BabySitter_Profile:
    resource: "@FrontGeneralBundle/Resources/config/routing/BabySitter.yml"
    prefix:   /baby_sitter_space

front_babysitter_liste:
    path:     /liste/{page}/{country}/{city}/{gender}/{languages}/{smoker}/{specialNeeds}/{provideSickCare}/{pets}/{homeWorkHelp}/{motCle}
    defaults:
        _controller: FrontGeneralBundle:BabySitter:liste
        page : 1
        country: all
        city: all
        gender: all
        languages: all
        smoker: all
        specialNeeds: all
        provideSickCare: all
        pets: all
        homeWorkHelp: all
        motCle: null

front_babysitter_liste_filtre:
    path:     /filtreBabySitter
    defaults: { _controller: FrontGeneralBundle:BabySitter:filtre }


front_babysitter_profile:
    path:     /babysitter/{slug}
    defaults: { _controller: FrontGeneralBundle:BabySitter:babysiter,page:1 }


front_babysitter_calendar:
    path:     /babysitter/calendar/{slug}
    defaults: { _controller: FrontGeneralBundle:BabySitter:calendar }


front_ajax_country_to_city:
    path:     /front_ajax_country_to_city
    defaults: { _controller: FrontGeneralBundle:BabySitter:ajaxCountryToCity }
