front_homepage:
    path:     /
    defaults: { _controller: FrontGeneralBundle:Default:homePage }

Front_BabySitter_Profile:
    resource: "@FrontGeneralBundle/Resources/config/routing/BabySitter.yml"
    prefix:   /baby_sitter_space

front_babysitter_liste:
    path:     /liste/{page}/{country}/{city}/{gender}/{languages}/{smoker}/{specialNeeds}/{provideSickCare}/{pets}/{homeWorkHelp}/{motCle}
    defaults:
        _controller: FrontGeneralBundle:BabySitter:liste
        page : 1
        country: all
        city: all
        gender: all
        languages: all
        smoker: all
        specialNeeds: all
        provideSickCare: all
        pets: all
        homeWorkHelp: all
        motCle: null

front_babysitter_liste_filtre:
    path:     /filtreBabySitter
    defaults: { _controller: FrontGeneralBundle:BabySitter:filtre }


front_babysitter_profile:
    path:     /babysitter/{slug}
    defaults: { _controller: FrontGeneralBundle:BabySitter:babysiter,page:1 }


front_babysitter_calendar:
    path:     /babysitter/calendar/{slug}
    defaults: { _controller: FrontGeneralBundle:BabySitter:calendar }


front_babysitter_sendToPaipal:
    path:     /babysitter/sendToPaipal/{id}
    defaults: { _controller: FrontGeneralBundle:BabySitter:sendToPaipal }


front_babysitter_booking:
    path:     /babysitter/calendar/{slug}/{year}/{month}/{day}
    defaults: { _controller: FrontGeneralBundle:BabySitter:booking }


front_ajax_country_to_city:
    path:     /front_ajax_country_to_city
    defaults: { _controller: FrontGeneralBundle:BabySitter:ajaxCountryToCity }


front_babysitter_sendToPaipal_notify:
    path:     /notify
    defaults: { _controller: FrontGeneralBundle:BabySitter:paypalNotify }


front_babysitter_sendToPaipal_ok:
    path:     /success
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'FrontGeneralBundle::succes.html.twig'


front_babysitter_sendToPaipal_ko:
    path:     /echec
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'FrontGeneralBundle::echec.html.twig'
