services:
    geolocation:
        class: Front\GeneralBundle\Services\GeoLocationService
        arguments:
            - @doctrine.orm.entity_manager
            - @session
            - @service_container
            - @mailer
            - @templating