services:
    interface:
        class: Front\GeneralBundle\Twig\FunctionExtension
        tags:
            - { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"

    geolocation:
        class: Front\GeneralBundle\Services\GeoLocationService
        arguments:
            - @doctrine.orm.entity_manager
            - @session
            - @service_container
            - @mailer
            - @templating